// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCSNHf4Ee4PBgprqldgy1siFF_nUspiHA',
    appId: '1:723619028507:web:ccbd48320f2f1d8b7822be',
    messagingSenderId: '723619028507',
    projectId: 'notes-app-26354',
    authDomain: 'notes-app-26354.firebaseapp.com',
    storageBucket: 'notes-app-26354.firebasestorage.app',
    measurementId: 'G-G2LX1V96WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASPSzpr359dG7vU8ClSC5r8YV0sqXz-2M',
    appId: '1:723619028507:android:97ced369b459bd377822be',
    messagingSenderId: '723619028507',
    projectId: 'notes-app-26354',
    storageBucket: 'notes-app-26354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVne62hkWrf00EDhg5JcDLKApkmyhtHsE',
    appId: '1:723619028507:ios:e2f446035f6971ac7822be',
    messagingSenderId: '723619028507',
    projectId: 'notes-app-26354',
    storageBucket: 'notes-app-26354.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVne62hkWrf00EDhg5JcDLKApkmyhtHsE',
    appId: '1:723619028507:ios:e2f446035f6971ac7822be',
    messagingSenderId: '723619028507',
    projectId: 'notes-app-26354',
    storageBucket: 'notes-app-26354.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCSNHf4Ee4PBgprqldgy1siFF_nUspiHA',
    appId: '1:723619028507:web:2a876951fe9a4a0b7822be',
    messagingSenderId: '723619028507',
    projectId: 'notes-app-26354',
    authDomain: 'notes-app-26354.firebaseapp.com',
    storageBucket: 'notes-app-26354.firebasestorage.app',
    measurementId: 'G-V2QMQS2K7K',
  );
}
